[package]
name = "FFXIV_Crafting_Optimizer"
version = "0.1.0"
authors = ["Morgan Lee <MorganLLee79@rpi.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
